---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
    
      - name: Loging to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Test
        run: docker-compose -f Docker-compose.yml run --rm app sh -c "python manage.py test"

      - name: Lint
        run: docker-compose -f Docker-compose.yml run --rm app sh -c "flake8"


      # - name: Test
      #   run: Docker-compose run --rm app sh -c "python manage.py test"
      #   # working-directory: recipe-app-api
  
      # - name: Lint
      #   run: Docker-compose run --rm app sh -c "flake8"